### ISSUE TITLE
Support rename to Permissions-Policy

### ISSUE THREAD

**Issue by adamchainz** [adamchainz/django-feature-policy#114]
The header is being renamed to `Permissions-Policy`. See:

* https://github.com/django/django/pull/11735
* https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy
* https://w3c.github.io/webappsec-feature-policy/ - spec was last updated 10 july to say Permissions-Policy

I think we could do a release that adds both `Feature-Policy` and `Permissions-Policy` as the headers. Idk about renaming the package.

**Comment by pope1ni** [comment]
Also note that the syntax of the header value has also changed; see https://github.com/django/django/pull/11735.

**Comment by justin-ven** [comment]
Would be great to have this feature, even as just a stop-gap until Permissions-Policy is added to Django core (https://github.com/django/django/pull/11735/commits/8bd5b9b05c85c09884a6335412061bb441a71d6d)
