### ISSUE TITLE
Ideas to reduce the CPU impact of this middleware

### ISSUE THREAD

**Issue by rik** [adamchainz/django-feature-policy#21]
I've had two ideas to save some CPU cycles but before implementing them, I wanted to check if you'd be interested in those changes:

1. Change `FEATURE_NAMES` to a set to speed up `if feature not in FEATURE_NAMES`
1. Generate and save the header in `__init__`. Django settings are not supposed to change so `__call__` could write the string into the header. That means using `django.test.signals.setting_changed` for testing purposes though.

**Comment by adamchainz** [comment]
Yeah both seem sensible. I doubt you can spot this middleware in your benchmarking though! If you want to tackle them in a PR, please feel free.

**Comment by rik** [comment]
I haven't benchmarked it and you are probably right. It's just that I saw those opportunities to not work on every request.
